\c film_app

INSERT INTO movies (title, year, description, poster_url, screenshot_url) VALUES ('Titanic', 2007, '84 years later, a 100 year-old woman named Rose DeWitt Bukater tells the story to her granddaughter Lizzy Calvert, Brock Lovett, Lewis Bodine, Bobby Buell and Anatoly Mikailavich on the Keldysh about her life set in April 10th 1912, on a ship called Titanic when young Rose boards the departing ship with the upper-class passengers and her mother, Ruth DeWitt Bukater, and her fiancé, Caledon Hockley. Meanwhile, a drifter and artist named Jack Dawson and his best friend Fabrizio De Rossi win third-class tickets to the ship in a game. And she explains the whole story from departure until the death of Titanic on its first and last voyage April 15th, 1912 at 2:20 in the morning.','https://imgc.allpostersimages.com/img/posters/titanic_u-L-F4S6CQ0.jpg?src=gp&w=300&h=375', 'https://i.ytimg.com/vi/Uf_DxHPSWhA/maxresdefault.jpg');


INSERT INTO movies (title, year, description, poster_url, screenshot_url) VALUES ('Black Panther', 2018,'After the death of his father, T/Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T/Challa/s mettle as king -- and as Black Panther -- gets tested when he/s drawn into a conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people.','https://ia.media-imdb.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', 'http://cdn.wegotthiscovered.com/wp-content/uploads/2017/10/black-panther-movie-image-9.jpg');

INSERT INTO movies (title, year, description, poster_url, screenshot_url) VALUES ('Silence of The Lambs',1992, 'Jodie Foster stars as Clarice Starling, a top student at the FBI/s training academy. Jack Crawford (Scott Glenn) wants Clarice to interview Dr. Hannibal Lecter (Anthony Hopkins), a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.',  'https://images-na.ssl-images-amazon.com/images/I/41dJipyydvL.jpg', 'https://plotandtheme.files.wordpress.com/2016/05/silence-of-the-lambs.png?w=1400');

INSERT INTO movies(title,year,description,poster_url, screenshot_url) VALUES ('No Country for Old Men',2007,'While out hunting, Llewelyn Moss (Josh Brolin) finds the grisly aftermath of a drug deal. Though he knows better, he cannot resist the cash left behind and takes it with him. The hunter becomes the hunted when a merciless killer named Chigurh (Javier Bardem) picks up his trail. Also looking for Moss is Sheriff Bell (Tommy Lee Jones), an aging lawman who reflects on a changing world and a dark secret of his own, as he tries to find and protect Moss.','https://images-na.ssl-images-amazon.com/images/I/51U1qJ70-ML.jpg',
'https://i.ytimg.com/vi/OLCL6OYbSTw/maxresdefault.jpg');

INSERT INTO movies(title,year,description,poster_url, screenshot_url) VALUES ('Kill Bill: Volume 1',2003,'The lead character, called "The Bride," was a member of the Deadly Viper Assassination Squad, led by her lover "Bill." Upon realizing she was pregnant with Bill/s child, "The Bride" decided to escape her life as a killer. She fled to Texas, met a young man, who, on the day of their wedding rehearsal was gunned down by an angry and jealous Bill (with the assistance of the Deadly Viper Assassination Squad). Four years later, "The Bride" wakes from a coma, and discovers her baby is gone. She, then, decides to seek revenge upon the five people who destroyed her life and killed her baby. The saga of Kill Bill Volume I begins.', 'https://ia.media-imdb.com/images/M/MV5BYTczMGFiOWItMjA3Mi00YTU5LWIwMDgtYTEzNjRkNDkwMTE2XkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_.jpg', 'http://www.digitaldingus.com/reviews/hd/0003/kbvol13_fullres.jpg');


INSERT INTO movies(title,year,description,poster_url, screenshot_url) VALUES ( 'Cloud Atlas', 2012, 'Everything is connected: an 1849 diary of an ocean voyage across the Pacific; letters from a composer to his lover; a thriller about a conspiracy at a nuclear power plant; a farce about a publisher in a nursing home; a rebellious clone in futuristic Korea; and the tale of a tribe living on post-apocalyptic Hawaii far in the future.',  'https://ia.media-imdb.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_SY1000_CR0,0,674,1000_AL_.jpg', 'https://static01.nyt.com/images/2012/10/26/arts/26CLOUD1/26CLOUD1-jumbo.jpg');

INSERT INTO movies(title,year,description,poster_url, screenshot_url) VALUES ('Monster/s Ball',2001,
  'Set in the Southern United States, "Monster/s Ball" is a tale of a racist white man, Hank, who falls in love with a black woman named Leticia. Ironically Hank is a prison guard working on Death Row who executed Leticia/s husband. Hank and Leticia/s interracial affair leads to confusion and new ideas for the two unlikely lovers.', 'https://ia.media-imdb.com/images/M/MV5BNTkyMzk3NTYtY2FiYy00MWIwLWIyYzctODIzNzVlOGQxZmYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg','https://i.ytimg.com/vi/Y-94HNhLJBs/maxresdefault.jpg');

INSERT INTO movies(title,year,description,poster_url, screenshot_url) VALUES ('Apocalypto', 2006, 'In the Maya civilization, a peaceful tribe is brutally attacked by warriors seeking slaves and human beings for sacrifice for their gods. Jaguar Paw hides his pregnant wife and his son in a deep hole nearby their tribe and is captured while fighting with his people. An eclipse spares his life from the sacrifice and later he has to fight to survive and save his beloved family.',
     'https://ia.media-imdb.com/images/M/MV5BMzhmNGMzMDMtZDM0Yi00MmVmLWExYjAtZDhjZjcxZDM0MzJhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,674,1000_AL_.jpg','http://s2.dmcdn.net/Inac0/1280x720--ib.jpg');

INSERT INTO movies(title,year,description,poster_url, screenshot_url) VALUES ('Interview with the Vampire: The Vampire Chronicles', 1994,'It hasn/t even been a year since a plantation owner named Louis lost his wife in childbirth. Both his wife and the infant died, and now he has lost his will to live. A vampire named Lestat takes a liking to Louis and offers him the chance to become a creature of the night: a vampire. Louis accepts, and Lestat drains Louis mortal blood and then replaces it with his own, turning Louis into a vampire. Louis must learn from Lestat the ways of the vampire.',  'https://ia.media-imdb.com/images/M/MV5BYThmYjJhMGItNjlmOC00ZDRiLWEzNjUtZjU4MjA3MzY0MzFmXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_SY1000_CR0,0,667,1000_AL_.jpg', 'https://movieplayer.net-cdn.it/images/2009/08/23/claudia-kirsten-dunst-louis-brad-pitt-e-lestat-tom-cruise-in-una-scena-del-film-interview-with-the-vampire-127952.jpg');

INSERT INTO movies(title,year,description,poster_url, screenshot_url) VALUES ('V for Vendetta',2005,  'In a future British tyranny, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow it with the help of a young woman.', 'https://ia.media-imdb.com/images/M/MV5BYzllMjJkODAtYjMwMi00YmNhLWFhYzAtZjZjODg5YzEwOGUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY999_CR0,0,679,999_AL_.jpg','https://nerdist.com/wp-content/uploads/2016/05/v-for-vendetta-FEAT.jpg');
